steps:
  # === Stage: Build ===
  # Build the Docker image using the Dockerfile in the specified source directory.
  # The image is tagged with the commit SHA for traceability.
  # --no-cache is used to ensure a clean build environment.
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA
      - src/rickbot
      - '-f'
      - src/rickbot/Dockerfile
    id: Build

  # === Stage: Push ===
  # Push the built Docker image to Google Artifact Registry.
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA
    id: Push

  # === Stage: Deploy ===
  # Deploy the new image to the Cloud Run service.
  # Uses 'gcloud run services update' which creates the service if it doesn't exist,
  # or updates it with the new image if it does.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$SHORT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--allow-unauthenticated'
      - '--max-instances=$_MAX_INSTANCES' # Limit the number of instances to 1
      - '--cpu-boost'
      - '--set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_REGION=$_DEPLOY_REGION,LOG_LEVEL=$_LOG_LEVEL,AUTH_REQUIRED=$_AUTH_REQUIRED,RATE_LIMIT=$_RATE_LIMIT'
      - '--service-account=rickbot-sa@${_AR_PROJECT_ID}.iam.gserviceaccount.com'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$SHORT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: rickbot
  _TRIGGER_ID: b614a57c-8d36-41af-b1aa-ff66aa0ffb9d
  _DEPLOY_REGION: europe-west4
  _LOG_LEVEL: INFO
  _MAX_INSTANCES: "1"
  _AR_HOSTNAME: europe-west4-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: rickbot-463118
  _AUTH_REQUIRED: "False"
  _RATE_LIMIT: "60"
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - rickbot
